linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck

linters-settings:
  errcheck:
    check-blank: false

issues:
  exclude-use-default: true

run:
  timeout: 5m
